### ISSUE TITLE
ORMReload Doesn't refresh the CFCLocation files

### ISSUE THREAD

**Issue by migueltarga** [lucee/extension-hibernate#35]
During a startup, if the app creates or moves any CFC file into one of the folder configured on orm.cfclocation and call ORMReload() it reloads the session but doesn't reload the resources/cfcs looks like it cached at the page context

Is that an expected behavior? if we do ORMReload in the subsequent request, it works fine.

thanks

**Comment by zspitzer** [comment]
Please use JIRA for bug reports, but as this is a question, please use the mailing list first
